# Generated by Django 4.1.5 on 2023-01-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_rewiev'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiev',
            new_name='Review',
        ),
    ]
